version: "3.9"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8001:8000"

  product-service:
    build: ./services/product-service
    ports:
      - "8002:8000"

  order-service:
    build: ./services/order-service
    ports:
      - "8003:8000"

  payment-service:
    build: ./services/payment-service
    ports:
      - "8004:8000"
